// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestDeloitteApp.Data;

#nullable disable

namespace TestDeloitteApp.Data.Migrations
{
    [DbContext(typeof(TestDeloitteAppContext))]
    partial class TestDeloitteAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("TestDeloitteApp.Models.CaseDiary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Father")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FatherViolence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Function")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mother")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MotherViolence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Open")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubFunction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CaseDiaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaseId = "2323",
                            DueDate = new DateTime(2024, 7, 18, 10, 24, 22, 203, DateTimeKind.Local).AddTicks(3422),
                            Father = "asassa",
                            FatherViolence = false,
                            Function = "aaaaa",
                            Mother = "asassa",
                            MotherViolence = true,
                            Open = "Yes",
                            Prim = "No",
                            StartDate = new DateTime(2024, 7, 18, 10, 24, 22, 203, DateTimeKind.Local).AddTicks(3378),
                            SubFunction = "bbbb"
                        },
                        new
                        {
                            Id = 2,
                            CaseId = "2323",
                            DueDate = new DateTime(2024, 7, 18, 10, 24, 22, 203, DateTimeKind.Local).AddTicks(3431),
                            Father = "asassa",
                            FatherViolence = false,
                            Function = "aaaaa",
                            Mother = "asassa",
                            MotherViolence = true,
                            Open = "Yes",
                            Prim = "No",
                            StartDate = new DateTime(2024, 7, 18, 10, 24, 22, 203, DateTimeKind.Local).AddTicks(3429),
                            SubFunction = "bbbb"
                        },
                        new
                        {
                            Id = 3,
                            CaseId = "2323",
                            DueDate = new DateTime(2024, 7, 18, 10, 24, 22, 203, DateTimeKind.Local).AddTicks(3439),
                            Father = "asassa",
                            FatherViolence = false,
                            Function = "aaaaa",
                            Mother = "asassa",
                            MotherViolence = true,
                            Open = "Yes",
                            Prim = "No",
                            StartDate = new DateTime(2024, 7, 18, 10, 24, 22, 203, DateTimeKind.Local).AddTicks(3436),
                            SubFunction = "bbbb"
                        },
                        new
                        {
                            Id = 4,
                            CaseId = "2323",
                            DueDate = new DateTime(2024, 7, 18, 10, 24, 22, 203, DateTimeKind.Local).AddTicks(3447),
                            Father = "asassa",
                            FatherViolence = false,
                            Function = "aaaaa",
                            Mother = "asassa",
                            MotherViolence = true,
                            Open = "Yes",
                            Prim = "No",
                            StartDate = new DateTime(2024, 7, 18, 10, 24, 22, 203, DateTimeKind.Local).AddTicks(3444),
                            SubFunction = "bbbb"
                        },
                        new
                        {
                            Id = 5,
                            CaseId = "2323",
                            DueDate = new DateTime(2024, 7, 18, 10, 24, 22, 203, DateTimeKind.Local).AddTicks(3453),
                            Father = "asassa",
                            FatherViolence = false,
                            Function = "aaaaa",
                            Mother = "asassa",
                            MotherViolence = true,
                            Open = "Yes",
                            Prim = "No",
                            StartDate = new DateTime(2024, 7, 18, 10, 24, 22, 203, DateTimeKind.Local).AddTicks(3450),
                            SubFunction = "bbbb"
                        },
                        new
                        {
                            Id = 6,
                            CaseId = "111",
                            DueDate = new DateTime(2024, 7, 18, 10, 24, 22, 203, DateTimeKind.Local).AddTicks(3460),
                            Father = "asassa",
                            FatherViolence = false,
                            Function = "aaaaa",
                            Mother = "asassa",
                            MotherViolence = true,
                            Open = "Yes",
                            Prim = "No",
                            StartDate = new DateTime(2024, 7, 18, 10, 24, 22, 203, DateTimeKind.Local).AddTicks(3458),
                            SubFunction = "bbbb"
                        },
                        new
                        {
                            Id = 7,
                            CaseId = "111",
                            DueDate = new DateTime(2024, 7, 18, 10, 24, 22, 203, DateTimeKind.Local).AddTicks(3467),
                            Father = "asassa",
                            FatherViolence = false,
                            Function = "aaaaa",
                            Mother = "asassa",
                            MotherViolence = true,
                            Open = "Yes",
                            Prim = "No",
                            StartDate = new DateTime(2024, 7, 18, 10, 24, 22, 203, DateTimeKind.Local).AddTicks(3464),
                            SubFunction = "bbbb"
                        });
                });

            modelBuilder.Entity("TestDeloitteApp.Models.CaseDiaryNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaseDiaryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Line1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Line10")
                        .HasColumnType("TEXT");

                    b.Property<string>("Line2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Line3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Line4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Line5")
                        .HasColumnType("TEXT");

                    b.Property<string>("Line6")
                        .HasColumnType("TEXT");

                    b.Property<string>("Line7")
                        .HasColumnType("TEXT");

                    b.Property<string>("Line8")
                        .HasColumnType("TEXT");

                    b.Property<string>("Line9")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CaseDiaryNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
